# Generated by Django 5.1.15 on 2026-02-28 17:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('how_heard', models.CharField(blank=True, max_length=100)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Signup / Contact Submission',
                'verbose_name_plural': 'Signup / Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_chamber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_chambers', to='crm.chamber')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('men_reborn', 'Men Reborn (Launch)'), ('man_at_altar', 'Man at the Altar (Monthly Prayer)'), ('leadership_summit', 'Leadership Summit (Bi-Annual)'), ('gathering', 'Gathering of the Chambers (Annual)'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chamber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='crm.chamber')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('active', 'Active'), ('inactive', 'Inactive')], default='prospect', max_length=20)),
                ('role', models.CharField(choices=[('member', 'Member'), ('foundation_support', 'Foundation Support'), ('iron_circle_leader', 'Iron Circle Leader'), ('media_expert', 'Media & Social Media Expert'), ('admin_pm', 'Admin & Project Manager'), ('chamber_lead', 'Chamber Lead'), ('elder', 'Elder')], default='member', max_length=30)),
                ('how_heard', models.CharField(blank=True, choices=[('social_media', 'Social Media'), ('church', 'Church'), ('friend', 'Friend / Word of Mouth'), ('event', 'Event'), ('website', 'Website'), ('other', 'Other')], max_length=20)),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('church_membership_years', models.PositiveIntegerField(blank=True, help_text='How many years the member has been active in their church', null=True)),
                ('notes', models.TextField(blank=True)),
                ('reason_for_joining', models.TextField(blank=True, help_text='Why they want to be part of TCM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chamber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='crm.chamber')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IronCircle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('meeting_day', models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('meeting_time', models.TimeField(blank=True, null=True)),
                ('meeting_location', models.CharField(blank=True, max_length=200)),
                ('is_open', models.BooleanField(default=True, help_text='Whether the circle is accepting new members')),
                ('max_members', models.PositiveIntegerField(default=5)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chamber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circles', to='crm.chamber')),
                ('circle_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_circles', to='crm.member')),
                ('members', models.ManyToManyField(blank=True, related_name='circles', to='crm.member')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='chamber',
            name='chamber_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_chambers', to='crm.member'),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('category', models.CharField(choices=[('doctrine', 'Chamber Doctrine'), ('testimony', 'Testimony'), ('devotional', 'Devotional'), ('update', 'Movement Update'), ('teaching', 'Teaching')], default='teaching', max_length=20)),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/')),
                ('is_published', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='crm.member')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='crm.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendance', to='crm.member')),
            ],
            options={
                'unique_together': {('event', 'member')},
            },
        ),
    ]
