# Generated by Django 5.1.15 on 2026-02-28 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(choices=[('onboarding', 'Onboarding Agent'), ('crm_pipeline', 'CRM Pipeline Agent'), ('event_manager', 'Event Management Agent'), ('iron_circle', 'Iron Circle Management Agent'), ('social_media', 'Social Media Agent'), ('leadership', 'Leadership Pipeline Agent')], max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Turn this agent on or off')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Agent-specific settings as JSON (e.g. timing, thresholds)')),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent Configuration',
                'verbose_name_plural': 'Agent Configurations',
                'ordering': ['agent_name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(choices=[('welcome', 'Welcome Email'), ('follow_up_day_2', 'Follow-up - Day 2'), ('follow_up_day_5', 'Follow-up - Day 5'), ('follow_up_day_10', 'Follow-up - Day 10'), ('interview_reminder', 'Interview Reminder'), ('event_reminder_7d', 'Event Reminder - 7 Days'), ('event_reminder_1d', 'Event Reminder - 1 Day'), ('event_thank_you', 'Event Thank You'), ('circle_welcome', 'Iron Circle Welcome'), ('circle_meeting_reminder', 'Circle Meeting Reminder'), ('inactive_warning', 'Inactive Member Warning')], max_length=30, unique=True)),
                ('subject', models.CharField(help_text='Email subject line. Use {{ name }} for personalisation.', max_length=300)),
                ('body_html', models.TextField(help_text='HTML email body. Available variables: {{ name }}, {{ first_name }}, {{ email }}, {{ city }}, {{ event_name }}, {{ event_date }}, {{ circle_name }}, {{ leader_name }}, {{ interview_date }}')),
                ('body_text', models.TextField(blank=True, help_text='Plain text fallback. Leave blank to auto-generate from HTML.')),
                ('from_name', models.CharField(default='The Chambers of Men', max_length=100)),
                ('from_email', models.EmailField(default='info@thechamberofmen.com', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['template_key'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='interview_scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Date and time of scheduled intro call', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='last_engagement_date',
            field=models.DateField(blank=True, help_text='Last event attendance, circle meeting, or meaningful interaction', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='onboarding_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('welcome_sent', 'Welcome Email Sent'), ('follow_up_1', 'Follow-up 1 Sent (Day 2)'), ('follow_up_2', 'Follow-up 2 Sent (Day 5)'), ('follow_up_3', 'Final Follow-up Sent (Day 10)'), ('interview_scheduled', 'Interview Scheduled'), ('onboarded', 'Fully Onboarded')], default='not_started', help_text='Current position in the onboarding email sequence', max_length=30),
        ),
        migrations.CreateModel(
            name='AdminFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('inactive_member', 'Inactive Member'), ('circle_capacity', 'Circle at Capacity'), ('low_event_rsvp', 'Low Event RSVP'), ('missing_data', 'Missing Member Data'), ('onboarding_stalled', 'Onboarding Stalled'), ('leadership_candidate', 'Leadership Candidate'), ('general', 'General Alert')], max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('agent_name', models.CharField(help_text='Which agent raised this flag', max_length=30)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_by', models.CharField(blank=True, max_length=200)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_flags', to='crm.member')),
            ],
            options={
                'verbose_name': 'Admin Flag / Alert',
                'verbose_name_plural': 'Admin Flags / Alerts',
                'ordering': ['is_resolved', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CircleAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('joined', 'Joined Circle'), ('left', 'Left Circle'), ('transferred', 'Transferred'), ('promoted_leader', 'Promoted to Leader')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('performed_by', models.CharField(blank=True, help_text='Agent or admin who made the change', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='crm.ironcircle')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_history', to='crm.member')),
            ],
            options={
                'verbose_name': 'Circle Assignment History',
                'verbose_name_plural': 'Circle Assignment History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadershipProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_role', models.CharField(choices=[('member', 'Member'), ('foundation_support', 'Foundation Support'), ('iron_circle_leader', 'Iron Circle Leader'), ('media_expert', 'Media & Social Media Expert'), ('admin_pm', 'Admin & Project Manager'), ('chamber_lead', 'Chamber Lead'), ('elder', 'Elder')], max_length=30)),
                ('to_role', models.CharField(choices=[('member', 'Member'), ('foundation_support', 'Foundation Support'), ('iron_circle_leader', 'Iron Circle Leader'), ('media_expert', 'Media & Social Media Expert'), ('admin_pm', 'Admin & Project Manager'), ('chamber_lead', 'Chamber Lead'), ('elder', 'Elder')], max_length=30)),
                ('reason', models.TextField(blank=True, help_text='Why this progression was recommended or made')),
                ('recommended_by', models.CharField(blank=True, help_text='Agent or leader who recommended', max_length=200)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=200)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_history', to='crm.member')),
            ],
            options={
                'verbose_name': 'Leadership Progression',
                'verbose_name_plural': 'Leadership Progressions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('event_attendance', 'Event Attendance'), ('circle_meeting', 'Circle Meeting'), ('email_opened', 'Email Opened'), ('email_clicked', 'Email Link Clicked'), ('form_submission', 'Form Submission'), ('interview_completed', 'Interview Completed'), ('role_assigned', 'Role Assigned'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='crm.member')),
                ('related_circle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.ironcircle')),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.event')),
            ],
            options={
                'verbose_name': 'Member Activity Log',
                'verbose_name_plural': 'Member Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('twitter', 'X / Twitter')], max_length=20)),
                ('caption', models.TextField(help_text='Post caption / description')),
                ('hashtags', models.TextField(blank=True, help_text='Hashtags separated by spaces')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('external_post_id', models.CharField(blank=True, help_text='ID from the platform after publishing', max_length=200)),
                ('engagement_data', models.JSONField(blank=True, default=dict, help_text='Likes, shares, comments, views')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_post', models.ForeignKey(blank=True, help_text='Blog post this was generated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='crm.blogpost')),
            ],
            options={
                'verbose_name': 'Social Media Post',
                'verbose_name_plural': 'Social Media Posts',
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(help_text='Which agent performed this action', max_length=30)),
                ('action', models.CharField(help_text='What the agent did', max_length=200)),
                ('detail', models.TextField(blank=True, help_text='Additional details or error messages')),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('email_sent_to', models.EmailField(blank=True, help_text='Email address if an email was sent', max_length=254)),
                ('template_used', models.CharField(blank=True, help_text='Email template key used', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, help_text='The member this action relates to (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_logs', to='crm.member')),
            ],
            options={
                'verbose_name': 'Agent Task Log',
                'verbose_name_plural': 'Agent Task Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
