# Generated by Django 5.1.15 on 2026-08-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_align_agent_framework_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='reason_for_joining',
            field=models.TextField(blank=True, help_text='Why they want to be part of Chambers of Men'),
        ),
    ]
